{{- if .Values.enabled }}
{{- if eq (len .Values.spec) 0 }}
{{- fail "cluster-autoscaler requires a non-empty spec when enabled is true." }}
{{- end }}
apiVersion: autoscaling.openshift.io/v1
kind: ClusterAutoscaler
metadata:
  name: {{ .Values.name | default "default" | quote }}
spec:
{{ toYaml .Values.spec | indent 2 }}
{{- end }}
