---
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSetting
metadata:
  name: {{ .Values.resourceCommonName }}
  namespace: openshift-compliance
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "4"
    "helm.sh/hook": ""
    "helm.sh/hook-weight": "4"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
rawResultStorage:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  pvAccessModes:
    - ReadWriteOnce
  rotation: 3
  size: 2Gi
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
schedule: {{ .Values.scanSchedule }}
suspend: false
roles:
  - master
  - worker
maxRetryOnTimeout: 3
scanTolerations:
  - operator: Exists
scanLimits:
  memory: 1500Mi
debug: {{ .Values.enableDebug }}
showNotApplicable: false
autoUpdateRemediations: true
strictNodeScan: true
autoApplyRemediations: {{ .Values.autoApplyRemediations }}
timeout: 30m
priorityClass: compliance-high-priority
remediationEnforcement: "all"

