---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/enforce: privileged
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "0"
    "helm.sh/hook": ""
    "helm.sh/hook-weight": "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
    openshift.io/node-selector: ""
  name: nginx-ingress
