---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  targetNamespaces:
   - nginx-ingress