# Create SCC for IC resources
{{ range $controller := .Values.controllers }}
---
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegedContainer: true
allowPrivilegeEscalation: true
allowedCapabilities: 
- '*'
apiVersion: security.openshift.io/v1
defaultAddCapabilities: [] 
fsGroup: 
  type: RunAsAny
groups: 
- system:cluster-admins
- system:nodes
kind: SecurityContextConstraints
metadata:
  name: "{{ $controller.name }}"
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser: 
  type: RunAsAny
seLinuxContext: 
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups: 
  type: RunAsAny
users:
 - "system:serviceaccount:{{ $controller.namespace }}:{{ $controller.name }}"
 - "system:serviceaccount:{{ $controller.namespace }}:{{ $controller.name }}-operator-controller-manager"
 - "system:serviceaccount:{{ $controller.namespace }}:{{ $controller.name }}-controller-manager"
allowedCapabilities:
  - NET_BIND_SERVICE
{{ end }}