# Create SCC for IC resources
{{ range $controller := .Values.controllers }}
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: "{{ $controller.namespace }}-{{ $controller.name }}"
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 101
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
seccompProfiles:    
- runtime/default
volumes:
 - secret
requiredDropCapabilities:
 - ALL
users:
 - "system:serviceaccount:{{ $controller.namespace }}:{{ $controller.name }}"
 - "system:serviceaccount:{{ $controller.namespace }}:{{ $controller.name }}-operator-controller-manager"
 - "system:serviceaccount:{{ $controller.namespace }}:{{ $controller.name }}-controller-manager"
allowedCapabilities:
  - NET_BIND_SERVICE
{{ end }}