{{ range $controller := .Values.controllers }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ $controller.ingressClassName }}-monitoring-edit"
  namespace: {{ $controller.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "3"
    "helm.sh/hook": ""
    "helm.sh/hook-weight": "3"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true,CreateNamespace=true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
subjects:
- kind: ServiceAccount
  name: "{{ $controller.ingressClassName }}-operator-controller-manager"
  namespace: {{ $controller.namespace }}
- kind: ServiceAccount
  name: "{{ $controller.ingressClassName }}"
  namespace: {{ $controller.namespace }}
- kind: ServiceAccount
  name: "nginx-ingress"
  namespace: {{ $controller.namespace }}
{{ end }}