apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.resourceNamePrefix }}-cluster-create-pull-secret"
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  pull_secret_json: |-
    {{ .Files.Get "secrets/pull-secret.json" | b64enc | indent 4 }}