---
apiVersion: v1
kind: ConfigMap
metadata:
  name: change-storage-class-config
  namespace: {{ .Values.namespace }}
  labels:
    velero.io/plugin-config: ""
    velero.io/change-storage-class: RestoreItemAction
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
data:
  {{ .Values.storageClassMapping.oldStorageClassName }}: {{ .Values.storageClassMapping.newStorageClassName }}