{{ if .Values.tlsCerts.enable }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.tlsCerts.caKVSecretName }}
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  labels:
    app.kubernetes.io/part-of: {{ .Values.namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: "{{ .Values.keyVaultName }}"
  data:
    - secretKey: tls_crt
      remoteRef:
        key: "secret/{{ .Values.tlsCerts.caKVSecretName }}"
  target:
    name: {{ .Values.tlsCerts.caKVSecretName }}
    creationPolicy: "Owner"
    template:
      # Possible Values: "Opaque", "kubernetes.io/dockerconfigjson", "kubernetes.io/tls", "kubernetes.io/ssh-auth"
      type: Opaque
      mergePolicy: Replace
      data:
        tls.crt: "{{ `{{ .tls_crt }}` }}"
{{ end }}