---
apiVersion: batch/v1
kind: Job
metadata:
  name: "enable-health-checks-on-argo-apps"
  namespace: openshift-gitops
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
    "helm.sh/hook": pre-install
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  template:
    spec:
      serviceAccountName: openshift-gitops-argocd-application-controller
      serviceAccount: openshift-gitops-argocd-application-controller
      restartPolicy: OnFailure
      containers:
      - name: "enable-health-checks-on-argo-apps"
        image: registry.redhat.io/openshift4/ose-tools-rhel9
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: "RuntimeDefault"
          capabilities:
            drop: [ALL]
        env:
        - name: HEALTH_CHECK_CONFIG_KEY
          value: "resource.customizations.health.argoproj.io_Application"
        command:
        - /bin/sh
        - -c
        - |
            set -e

            echo "==> Update argocd-cm configmap to enable app health check"

            cat <<EOF > /tmp/$HEALTH_CHECK_CONFIG_KEY
            hs = {}
            hs.status = "Progressing"
            hs.message = ""
            if obj.status ~= nil then
              if obj.status.health ~= nil then
                hs.status = obj.status.health.status
                if obj.status.health.message ~= nil then
                  hs.message = obj.status.health.message
                end
              end
            end
            return hs
            EOF

            cat /tmp/$HEALTH_CHECK_CONFIG_KEY

            oc -n openshift-gitops set data configmap/argocd-cm --from-file=$HEALTH_CHECK_CONFIG_KEY=/tmp/$HEALTH_CHECK_CONFIG_KEY
