---
apiVersion: batch/v1
kind: Job
metadata:
  name: "enable-health-checks-on-argo-apps"
  namespace: openshift-gitops
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  template:
    spec:
      serviceAccountName: openshift-gitops-argocd-application-controller
      serviceAccount: openshift-gitops-argocd-application-controller
      restartPolicy: OnFailure
      containers:
      - name: "enable-health-checks-on-argo-apps"
        image: registry.redhat.io/openshift4/ose-tools-rhel9
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: "RuntimeDefault"
          capabilities:
            drop: [ALL]
        env:
        - name: HEALTH_CHECK_CONFIG_KEY
          value: "resource.customizations.health.argoproj.io_Application"
        command:
        - /bin/sh
        - -c
        - |
            set -e

            echo "==> Update argocd-cm configmap to enable app health check"

            cat <<EOF > /tmp/$HEALTH_CHECK_CONFIG_KEY
            {{ .Files.Get "configs/app-health-check.lua" | indent 14 }}
            EOF

            oc -n openshift-config set data configmap/argocd-cm --from-file=/tmp/$HEALTH_CHECK_CONFIG_KEY
