---
apiVersion: config.openshift.io/v1 
kind: ImageDigestMirrorSet 
metadata:
  name: day2-gitops
  annotations:
    # argocd.argoproj.io/sync-wave: "0"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  imageDigestMirrors:
  {{ range $mirrorItem := .Values.imageMirrorsConfig }}
  - mirrors:
    {{ toYaml $mirrorItem.localReferences | nindent 6 }}
    source: {{ $mirrorItem.sourceReference }} 
    mirrorSourcePolicy: AllowContactingSource 
  {{ end }}