---
apiVersion: config.openshift.io/v1 
kind: ImageDigestMirrorSet 
metadata:
  name: ubi9repo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  imageDigestMirrors:
  {{ range $mirrorItem := .Values.imageMirrorsConfig }}
  - mirrors:
    {{ toYaml $mirrorItem.localReferences | nindent 6 }}
    source: {{ $mirrorItem.sourceReference }} 
    mirrorSourcePolicy: AllowContactingSource 
  {{ end }}