---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "999-splunk-otel-collector"
  namespace: openshift-gitops
  finalizers:
   - resources-finalizer.argocd.argoproj.io
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  labels:
    app.kubernetes.io/part-of: {{ .Values.resourceNamePrefix }}
spec:
  project: default

  source:
    repoURL: {{ .Values.helmChart.repoURL }}
    targetRevision: {{ .Values.helmChart.targetRevision }}
    chart: {{ .Values.helmChart.name }}
    helm:
      valuesObject:
        # Complete var list: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/values.yaml

        clusterName: {{ .Values.clusterName }} # REQUIRED
        namespaceOverride: {{ .Values.namespaceOverride }}
        cloudProvider: {{ .Values.cloudProvider }} # {aws|azure|gke}
        distribution: {{ .Values.distribution }} # {eks, aks, eks/fargate,..}
        environment: {{ .Values.environment }}
        logsEnabled: {{ .Values.logsEnabled }}
        metricsEnabled: {{ .Values.metricsEnabled }}
        tracesEnabled: {{ .Values.tracesEnabled }}

        splunkPlatform:
          endpoint: {{ .Values.splunkPlatform.endpoint }} # REQUIRED
          index: {{ .Values.splunkPlatform.index }} # REQUIRED
          insecureSkipVerify: {{ .Values.splunkPlatform.insecureSkipVerify }}
          source: {{ .Values.splunkPlatform.source }}
          maxConnections: {{ .Values.splunkPlatform.maxConnections }}
          disableCompression: {{ .Values.splunkPlatform.disableCompression }}
          timeout: {{ .Values.splunkPlatform.timeout }}
          idleConnTimeout: {{ .Values.splunkPlatform.idleConnTimeout }}

          retryOnFailure:
            enabled: {{ .Values.splunkPlatform.retryOnFailure.enabled }}
            initialInterval: {{ .Values.splunkPlatform.retryOnFailure.initialInterval }}
            maxInterval: {{ .Values.splunkPlatform.retryOnFailure.maxInterval }}
            maxElapsedTime: {{ .Values.splunkPlatform.retryOnFailure.maxElapsedTime }}

        logsEngine: {{ .Values.logsEngine }}
        secret:
          create: false
          name: {{ .Values.secret.name }}

        logsCollection:

          # Container logs collection
          containers:
            enabled: {{ .Values.logsCollection.containers.enabled }}
            containerRuntime: {{ .Values.logsCollection.containers.containerRuntime }}
            # Boolean for ingesting the agent's own log
            excludeAgentLogs: {{ .Values.logsCollection.containers.excludeAgentLogs }}

          # Configuration for collecting journald logs using otel collector
          journald:
            enabled: {{ .Values.logsCollection.journald.enabled }}
            directory: {{ .Values.logsCollection.journald.directory }}
            units:
              - name: kubelet
                priority: info
              - name: docker
                priority: info
              - name: containerd
                priority: info
              - name: cri-o
                priority: info
            # Route journald logs to its own Splunk Index by specifying the index value below, else leave it blank. Please make sure the index exist in Splunk and is configured to receive HEC traffic. Not applicable to Splunk Observability.
            index: ""

        agent:
          enabled: true
          service:
            enabled: true
          extraEnvs: 
            {{ toYaml .Values.agent.extraEnvs | nindent 12 }}
          extraVolumes: 
            {{ toYaml .Values.agent.extraVolumes | nindent 12 }}
          extraVolumeMounts: 
            {{ toYaml .Values.agent.extraVolumeMounts | nindent 12 }}

        rbac:
          create: {{ .Values.rbac.create }}

        tolerations: 
          {{ toYaml .Values.tolerations | nindent 10 }}

        securityContextConstraints:
          create: {{ .Values.securityContextConstraints.create }}

  # Destination cluster and namespace to deploy the application
  destination:
    # name: change-me
    name: in-cluster
    namespace: {{ .Values.namespaceOverride }}
    
  # NO NEED TO CHANGE BELOW PARAMS

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 900s


  # Apply metadata to namespaces
  # managedNamespaceMetadata:
  #   labels:
  #     argocd.argoproj.io/managed-by: openshift-gitops
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '0'

  ignoreDifferences:
  - group: operators.coreos.com/v1alpha1
    kind: Subscription
    jqPathExpressions:
      - '.spec.status'

  revisionHistoryLimit: 10