enabled: false
config:
  name: cluster
  external_secrets_namespace: external-secrets-operator
  refresh_interval: 1h
  cluster_secret_stores:
    - name: platform-secrets
      spec:
        provider:
          azurekv:
            authType: WorkloadIdentity
            tenantId: changeme
            vaultUrl: https://changeme.vault.azure.net
            serviceAccountRef:
              name: azure-key-vault-auth
              namespace: external-secrets-operator
            authSecretRef:
              clientId:
                name: azure-key-vault-auth
                namespace: ocp-tf-resources
                key: client-id
              tenantId:
                name: azure-key-vault-auth
                namespace: ocp-tf-resources
                key: tenant-id
certManager:
  enabled: false
