---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "{{ .Values.keyVaultName | lower }}"
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  provider:
    azurekv:
      tenantId: {{ .Values.provider.azurekv.tenantID }}
      vaultUrl: {{ .Values.provider.azurekv.vaultURL }}
      authSecretRef:
        clientId:
          name: cluster-sp-secret
          key: client_id
        clientSecret:
          name: cluster-sp-secret
          key: client_secret