---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: secrets-store-csi-driver-operator
  namespace: openshift-cluster-csi-drivers
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "2"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
    openshift.io/node-selector: ""
spec:
  channel: {{ .Values.operator.subscriptionChannel }}
  installPlanApproval: Automatic
  name: secrets-store-csi-driver-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace