---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Values.registriesCertsConfigMap }}-secret-to-configma-copy"
  namespace: openshift-gitops
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "1"
    "helm.sh/hook": ""
    "helm.sh/hook-weight": "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  schedule: "{{ .Values.patchSchedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            argocd.argoproj.io/managed-by: openshift-gitops
            app.kubernetes.io/part-of: aro-gitops
        spec:
          serviceAccountName: openshift-gitops-argocd-application-controller
          serviceAccount: openshift-gitops-argocd-application-controller
          restartPolicy: OnFailure
          containers:
          - name: "{{ .Values.registriesCertsConfigMap }}-secret-to-configma-copy"
            image: registry.redhat.io/openshift4/ose-tools-rhel8:{{ .Values.ocpVersion }}
            securityContext:
              allowPrivilegeEscalation: false
              seccompProfile:
                type: "RuntimeDefault"
              capabilities:
                drop: [ALL]
            command:
            - /bin/sh
            - -c
            - |
                set -e

                echo "==> Fetch registries certificates secret..."
                oc -n openshift-config extract secret/{{ .Values.registriesCertsConfigMap }} --to=/tmp/{{ .Values.registriesCertsConfigMap }} --confirm=true

                echo "==> Create registries certificates configmap..."
                oc -n openshift-config create configmap {{ .Values.registriesCertsConfigMap }} --from-file=/tmp/{{ .Values.registriesCertsConfigMap }} --dry-run=client -oyaml | oc apply -f -
