---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  labels:
    app.kubernetes.io/part-of: {{ .Values.namespace }}
spec:
  targetNamespaces:
    - {{ .Values.namespace }}