# Used for the java-cicd-tools runner - Duplicate this file to add other runners
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: java-cicd-tools
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  labels:
    app.kubernetes.io/part-of: {{ .Values.namespace }}
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: java-cicd-tools
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  labels:
    app.kubernetes.io/part-of: {{ .Values.namespace }}
spec:
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM {{ .Values.runnerBuildImage }}

      RUN echo "==> Installing Azure CLI" && \
          dnf update -y && \
          rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
          dnf install -y https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm && \
          dnf install -y azure-cli

      RUN echo "==> Installing helm" && \
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && \
          chmod 700 get_helm.sh && \
          ./get_helm.sh && \
          helm version

      RUN echo "Installing JQ" && \
          dnf install -y jq && \
          jq --version

      RUN echo "Installing RedHat Build of OpenJDK. Multiple versions installed. Select your version at build time" && \
          dnf install java-1.8.0-openjdk-devel -y && \
          dnf install java-17-openjdk -y && \
          dnf install java-21-openjdk -y && \
          java -version


      RUN echo "==> Checking for oc, helm, jq programs" && \
          oc version --client && \
          helm version && \
          jq --version && \
          java -version

  output:
    to:
      kind: ImageStreamTag
      name: java-cicd-tools:latest

  strategy:
    dockerStrategy:
      forcePull: true

  triggers:
    - type: "Generic"
      generic:
        secretReference:
          name: "java-cicd-tools"
        allowEnv: true
---
kind: Secret
apiVersion: v1
metadata:
  name: "java-cicd-tools"
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  labels:
    app.kubernetes.io/part-of: {{ .Values.namespace }}
stringData:
  WebHookSecretKey: java-cicd-tools
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: java-cicd-tools-bc-trigger
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: java-cicd-tools-bc-trigger
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: java-cicd-tools-bc-trigger
  namespace: {{ .Values.namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: java-cicd-tools-bc-trigger
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  labels:
    app.kubernetes.io/part-of: {{ .Values.namespace }}
spec:
  completions: 3
  parallelism: 1
  ttlSecondsAfterFinished: 86400 # Every 24H, recycle jobs regardless of status
  template:
    spec:
      serviceAccount: java-cicd-tools-bc-trigger
      containers:
        - name: java-cicd-tools-bc-trigger
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          env:
            - name: BUILD_CONFIG_NAME
              value: "java-cicd-tools"
          command:
            - /bin/sh
            - -c
            - |-
              echo "Triggering the BuildConfig: '$BUILD_CONFIG_NAME'"
              sleep 15
              API_SERVER=$(oc whoami --show-server)
              oc delete builds --all --namespace {{ .Values.namespace }}
              sleep 15
              curl -X POST -k "$API_SERVER/apis/build.openshift.io/v1/namespaces/{{ .Values.namespace }}/buildconfigs/$BUILD_CONFIG_NAME/webhooks/$BUILD_CONFIG_NAME/generic"
      restartPolicy: OnFailure
  backoffLimit: 3
---