# Used for the nodejs-cicd-tools runner - Duplicate this file to add other runners
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nodejs-cicd-tools
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  labels:
    app.kubernetes.io/part-of: {{ .Values.namespace }}
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nodejs-cicd-tools
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  labels:
    app.kubernetes.io/part-of: {{ .Values.namespace }}
spec:
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
  runPolicy: SerialLatestOnly
  source:
    dockerfile: |-
      FROM {{ .Values.runnerBuildImage }}

      RUN echo "==> Installing Azure CLI" && \
          dnf update -y && \
          rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
          dnf install -y https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm && \
          dnf install -y azure-cli

      RUN echo "==> Installing helm" && \
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && \
          chmod 700 get_helm.sh && \
          ./get_helm.sh && \
          helm version

      RUN echo "Installing JQ" && \
          dnf install -y jq && \
          jq --version

      RUN echo "Installing NodeJS and NPM" && \
          dnf install nodejs npm -y && \
          node -v && \
          npm -v


      RUN echo "==> Checking for oc, helm, jq programs" && \
          oc version --client && \
          helm version && \
          jq --version

  output:
    to:
      kind: ImageStreamTag
      name: nodejs-cicd-tools:latest

  strategy:
    dockerStrategy:
      forcePull: true

  triggers:
    - type: "Generic"
      generic:
        secretReference:
          name: "nodejs-cicd-tools"
        allowEnv: true
---
kind: Secret
apiVersion: v1
metadata:
  name: "nodejs-cicd-tools"
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  labels:
    app.kubernetes.io/part-of: {{ .Values.namespace }}
stringData:
  WebHookSecretKey: nodejs-cicd-tools
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nodejs-cicd-tools-bc-trigger
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  labels:
    app.kubernetes.io/part-of: {{ .Values.namespace }}
spec:
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: nodejs-cicd-tools-bc-trigger
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          env:
            - name: BUILD_CONFIG_NAME
              value: "nodejs-cicd-tools"
          command:
            - /bin/sh
            - -c
            - |-
              echo "Triggering the BuildConfig: '$BUILD_CONFIG_NAME'"
              sleep 15
              API_SERVER=$(oc whoami --show-server)
              curl -X POST -k "$API_SERVER/apis/build.openshift.io/v1/namespaces/{{ .Values.namespace }}/buildconfigs/$BUILD_CONFIG_NAME/webhooks/$BUILD_CONFIG_NAME/generic"
      restartPolicy: OnFailure
  backoffLimit: 3
---