{{ range $runner := .Values.runners }}
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: "{{ $runner.name }}-scc"
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users: 
- "system:serviceaccount:{{ $.Values.namespace }}:{{ $runner.name }}"
volumes: 
- '*'
{{ end }}