---
{{ range $runner := .Values.gitlab.runners }}
apiVersion: apps.gitlab.com/v1beta2
kind: Runner
metadata:
  name: {{ $runner.name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  {{ if $.Values.tlsCerts.enable }}
  ca: {{ $.Values.tlsCerts.caKVSecretName }}
  {{ end }}
  gitlabUrl: {{ $.Values.gitlabUrl }}
  runUntagged: {{ $runner.runUntagged }}
  tags: {{ $runner.tags }}
  token: {{ $.Values.gitlabRunnerRegistrationTokenKVSecret }}
  config: {{ $runner.name }}
{{ end }}