---
apiVersion: imageregistry.operator.openshift.io/v1
kind: ImagePruner
metadata:
  name: gitlab-runners-resources-pruner
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "6"
    "helm.sh/hook": ""
    "helm.sh/hook-weight": "6"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  failedJobsHistoryLimit: 3
  ignoreInvalidImageReferences: true
  keepTagRevisions: 3
  logLevel: Normal
  schedule: '0 8 * * *'
  successfulJobsHistoryLimit: 3
  suspend: false