---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "2"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  channel: stable
  name: cluster-logging
  source: redhat-operators
  sourceNamespace: openshift-marketplace