{{ range $namespaceItem := .Values.serviceMesh.controlPlaneNamespaces }}
---
apiVersion: "{{ $.Values.serviceMesh.smmrAPIVersion }}"
kind: ServiceMeshMemberRoll
metadata:
  # name: "{{ $namespaceItem.name }}"
  name: "default"
  namespace: "{{ $namespaceItem.name }}"
  annotations:
    argocd.argoproj.io/sync-wave: "8"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  members:
    # a list of projects joined into the service mesh
    {{ toYaml $namespaceItem.rollMembers | nindent 4 }}
{{ end }}