---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-traces-write
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "35"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "35"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
rules:
  - apiGroups:
      - 'tempo.grafana.com'
    resources: 
     {{ range $tenant := .Values.tenants }}
      - {{ $tenant.name }}
    {{ end }}
    resourceNames:
      - traces
    verbs:
      - 'create' 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempostack-traces
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "35"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "35"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tempostack-traces-write
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: {{ .Values.operators.otel.namespace }}