{{ range $tenant := .Values.tenants }}
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: "{{ $tenant.name }}-otel-collector"
  namespace: {{ $.Values.operators.otel.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "36"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "36"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  mode: deployment
  serviceAccount: otel-collector
  config: |
      extensions:
        bearertokenauth:
          filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      exporters:
        otlp/{{ $tenant.name }}: 
          endpoint: "tempo-{{ $.Values.operators.tempo.name }}-gateway.{{ $.Values.operators.tempo.namespace }}.svc.cluster.local:8090"
          tls:
            insecure: false
            ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
          auth:
            authenticator: bearertokenauth
          headers:
            X-Scope-OrgID: "{{ $tenant.name }}"
        otlphttp/{{ $tenant.name }}: 
          endpoint: "https://tempo-{{ $.Values.operators.tempo.name }}-gateway.{{ $.Values.operators.tempo.namespace }}.svc.cluster.local:8080/api/traces/v1/{{ $tenant.name }}"
          tls:
            insecure: false
            ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
          auth:
            authenticator: bearertokenauth
          headers:
            X-Scope-OrgID: "{{ $tenant.name }}"
      service:
        extensions: [bearertokenauth]
        pipelines:
          traces:
            exporters:
              - otlp/{{ $tenant.name }}
              - otlphttp/{{ $tenant.name }}
---
{{ range $rollMember := $tenant.smcp.rollMembers }} 
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: "{{ $rollMember }}-otel-collector"
  namespace: {{ $.Values.operators.otel.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "36"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "36"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  mode: deployment
  serviceAccount: otel-collector
  config: |
      extensions:
        bearertokenauth:
          filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      exporters:
        otlp/{{ $rollMember }}: 
          endpoint: "tempo-{{ $.Values.operators.tempo.name }}-gateway.{{ $.Values.operators.tempo.namespace }}.svc.cluster.local:8090"
          tls:
            insecure: false
            ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
          auth:
            authenticator: bearertokenauth
          headers:
            X-Scope-OrgID: "{{ $rollMember }}"
        otlphttp/{{ $rollMember }}: 
          endpoint: "https://tempo-{{ $.Values.operators.tempo.name }}-gateway.{{ $.Values.operators.tempo.namespace }}.svc.cluster.local:8080/api/traces/v1/{{ $rollMember }}"
          tls:
            insecure: false
            ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
          auth:
            authenticator: bearertokenauth
          headers:
            X-Scope-OrgID: "{{ $rollMember }}"
      service:
        extensions: [bearertokenauth]
        pipelines:
          traces:
            exporters:
              - otlp/{{ $rollMember }}
              - otlphttp/{{ $rollMember }}
{{ end }}
{{ end }}