{{ range $namespaceItem := .Values.serviceMesh.controlPlaneNamespaces }}
---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: "{{ $namespaceItem.name }}"
  namespace: "{{ $namespaceItem.name }}"
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  strategy: production
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: true                                 # turn the cron job deployment on and off
      numberOfDays: 15                               # number of days to wait before deleting a record
      schedule: 55 23 * * *                       # cron expression for it to run
    elasticsearch:
      nodeCount: 2                                    # 2 Elastic Search Node
      storage:
        size: 5Gi
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          memory: 2Gi
      redundancyPolicy: ZeroRedundancy              # Index redundancy"
{{ end }}