---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.operators.tempo.name }}
  namespace: {{ .Values.operators.tempo.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "41"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "41"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  targetNamespaces:
    - {{ .Values.operators.tempo.namespace }}