---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.operators.tempo.azureBlob.storageKVSecretName  | lower }}
  namespace: {{ .Values.operators.tempo.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "7"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "7"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.keyVaultName }}
  data:
    - secretKey: account_access_key
      remoteRef:
        key: secret/{{ .Values.operators.tempo.azureBlob.storageKVSecretName }}
  target:
    name: {{ .Values.operators.tempo.azureBlob.storageKVSecretName | lower }}
    creationPolicy: "Owner"
    template:
      # Possible Values: "Opaque", "kubernetes.io/dockerconfigjson", "kubernetes.io/tls", "kubernetes.io/ssh-auth"
      type: Opaque
      data:
        azure_cloud_name: {{ .Values.operators.tempo.azureBlob.cloudName }}
        container: {{ .Values.operators.tempo.azureBlob.containerName }}
        account_name: {{ .Values.operators.tempo.azureBlob.accountName }}
        account_key: "{{ `{{ .account_access_key }}` }}"