{{- if eq .Values.provider.azurekv.authType "WorkloadIdentity" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.provider.azurekv.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    "helm.sh/hook-weight": "4"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
{{- end }}
