---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.openIDClientSecretKeyVaultSecretName }}
  namespace: openshift-config
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: "{{ .Values.keyVaultName }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: "secret/{{ .Values.openIDClientSecretKeyVaultSecretName }}"
  target:
    name: {{ .Values.openIDClientSecretKeyVaultSecretName }}
    creationPolicy: "Owner"
    template:
      # Possible Values: "Opaque", "kubernetes.io/dockerconfigjson", "kubernetes.io/tls", "kubernetes.io/ssh-auth"
      type: Opaque
      data:
        clientSecret: {{ .clientSecret }}