{{ if .Values.idp.openid.enable }}
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  annotations:
    # argocd.argoproj.io/sync-wave: "2"
    "helm.sh/hook": ""
    "helm.sh/hook-weight": "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  identityProviders:
  {{ range $openIDProvider := .Values.idp.openid.providers }}
    - name: {{ $openIDProvider.name }}
      mappingMethod: claim
      type: OpenID
      openID:
        clientID: {{ $openIDProvider.clientID }}
        clientSecret:
          name: {{ $openIDProvider.clientSecretKeyVaultSecretName }}
        extraScopes:
        - profile
        - openid
        extraAuthorizeParameters: 
          include_granted_scopes: "true"
        claims:
          preferredUsername: 
          - preferred_username
          - email
          name:
          - name
          - given_name
          email: 
          - email
          groups: 
          - groups
        issuer: {{ $openIDProvider.issuerURL }}
  {{ end }}
{{ end }}