# Source: https://github.com/grafana/tempo-operator/blob/main/docs/spec/tempo.grafana.com_tempostacks.yaml
---
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: {{ .Values.operators.tempo.name }}
  namespace: {{ .Values.operators.tempo.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "9"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "9"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  replicationFactor: 1 
  storageSize: 25Gi 
  storage:
    secret: 
      name: {{ .Values.operators.tempo.azureBlob.storageKVSecretName }}
      type: azure
  template:
    gateway: # Gateway defines the tempo gateway spec.
      enabled: true
      ingress:
        route:                           # Route defines the options for the OpenShift route.
          termination: "edge"            # Termination defines the termination type. The default is "edge".
        type: "route"
    queryFrontend:
      jaegerQuery:                       # JaegerQuery defines options specific to the Jaeger Query component.
        enabled: true
        authentication:                  # Authentication defines the options for the oauth proxy used to protect jaeger UI
          enabled: true
        ingress:                         # Ingress defines the options for the Jaeger Query ingress.
          route:                         # Route defines the options for the OpenShift route.
            termination: "edge"              # Termination defines the termination type. The default is "edge".
          type: "route"
        monitorTab:
          enabled: true 
          prometheusEndpoint: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091 
  resources: 
    total:
      limits:
        memory: 4Gi
        cpu: 1000m
  observability:                       
    grafana:                             
      createDatasource: true
  retention:                             
    global:                             
      traces: "720h"                   
  storageClassName: ""                 
  storageSize: "25Gi"
  tenants:
    mode: openshift
    authentication: []