---
# Source: service-mesh/templates/0-ossm-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "0"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: service-mesh-operator
---
# Source: service-mesh/templates/3-kiali-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "3"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "3"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: kiali-operator
---
# Source: service-mesh/templates/6-tempo-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "6"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "6"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: tempo-operator
---
# Source: service-mesh/templates/97-ossm-smcp-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "97"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "97"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: "sales-mesh"
---
# Source: service-mesh/templates/97-ossm-smcp-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "97"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "97"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: "product-development-mesh"
---
# Source: service-mesh/templates/9-tempo-stack-cr.yaml
# Source: https://github.com/grafana/tempo-operator/blob/main/docs/spec/tempo.grafana.com_tempostacks.yaml
---
# Source: service-mesh/templates/7-tempo-storage-secret-eso.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ossm-tempostack-traces
  namespace: tempo-operator
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "7"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "7"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: stig0015-dev-vault
  data:
    - secretKey: account_access_key
      remoteRef:
        key: secret/ossm-tempostack-traces
  target:
    name: ossm-tempostack-traces
    creationPolicy: "Owner"
    template:
      # Possible Values: "Opaque", "kubernetes.io/dockerconfigjson", "kubernetes.io/tls", "kubernetes.io/ssh-auth"
      type: Opaque
      data:
        azure_cloud_name: AzurePublicCloud
        container: ossm-tempostack-traces
        account_name: stig0015devtfstate
        account_key: "{{ .account_access_key }}"
---
# Source: service-mesh/templates/1-ossm-operator-group.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: servicemeshoperator
  namespace: service-mesh-operator
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "1"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  targetNamespaces: []
---
# Source: service-mesh/templates/4-kiali-operator-group.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kiali-ossm
  namespace: kiali-operator
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "4"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "4"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  targetNamespaces: []
---
# Source: service-mesh/templates/7-tempo-operator-group.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: tempo-product
  namespace: tempo-operator
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "7"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "7"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  targetNamespaces: []
---
# Source: service-mesh/templates/2-ossm-subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "2"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: servicemeshoperator
  namespace: service-mesh-operator
spec:
  channel: stable
  installPlanApproval: automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    nodeSelector: {}
resources:
  limits:
    cpu: 1000m
    memory: 4Gi
tolerations: {}
---
# Source: service-mesh/templates/5-kiali-subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "5"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "5"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: kiali-ossm
  namespace: kiali-operator
spec:
  channel: stable
  installPlanApproval: automatic
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    nodeSelector: {}
resources:
  limits:
    cpu: 1000m
    memory: 4Gi
tolerations: {}
---
# Source: service-mesh/templates/8-tempo-subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "8"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "8"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: tempo-product
  namespace: tempo-operator
spec:
  channel: stable
  installPlanApproval: automatic
  name: tempo-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    nodeSelector: {}
resources:
  limits:
    cpu: 1000m
    memory: 4Gi
tolerations: {}
---
# Source: service-mesh/templates/9-tempo-stack-cr.yaml
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempo-product
  namespace: tempo-operator
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "9"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "9"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  replicationFactor: 1 
  storageSize: 25Gi 
  storage:
    secret: 
      name: ossm-tempostack-traces
      type: azure
  template:
    gateway: # Gateway defines the tempo gateway spec.
      enabled: true
      ingress:
        route:                          
          termination: "edge"           
        type: "route"
    queryFrontend:
      jaegerQuery:
        enabled: true                 
        authentication:
          enabled: false                
        # ingress:                         
        #   route:                         
        #     termination: "edge"              
        #   type: "route"
        monitorTab:
          enabled: true 
          prometheusEndpoint: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091 
  resources: 
    total:
      limits:
        memory: 4Gi
        cpu: 1000m
  retention:                             
    global:                             
      traces: "720h"                   
  storageClassName: ""                 
  storageSize: "25Gi"
  tenants:
    mode: openshift
    authentication: []
---
# Source: service-mesh/templates/98-servicemesh-control-plane.yaml
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: "sales"
  namespace: "sales-mesh"
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "98"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "98"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  version: "v2.6"
  security:
    controlPlane:
      mtls: "true"
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
  general:
    logging:
      logAsJSON: true
      componentLevels:
        default: info
  profiles:
    - default
  proxy:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
    accessLogging:
      file:
        name: /dev/stdout
    networking:
      trafficControl:
        inbound: {}
        outbound:
          policy: REGISTRY_ONLY
  gateways:
    enabled: "true"
    egress:
      enabled: "true"
      runtime:
        deployment:
          autoScaling:
            enabled: true
            maxReplicas: 3
            minReplicas: 1
        pod: {}
      service: {}
    ingress:
      enabled: "true"
      runtime:
        deployment:
          autoScaling:
            enabled: true
            maxReplicas: 2
            minReplicas: 1
        pod: {}
      service: {}
    openshiftRoute:
      enabled: "true"
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: "true"
      install:
        config:
          env: {}
          envSecrets: {}
        persistence:
          storageClassName: ""
          accessMode: ReadWriteOnce
          capacity:
            requests:
              storage: 10Gi
          enabled: true
        service:
          metadata:
            annotations:
              service.alpha.openshift.io/serving-cert-secret-name: grafana-tls
          ingress:
            contextPath: /grafana
            tls:
              termination: reencrypt
    jaeger:
      install:
        enabled: "true"
    kiali:
      enabled: "true"
      name: kiali
      install:
        dashboard:
          viewOnly: false
        deployment:
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
        service:
          ingress:
            enabled: true
    prometheus:
      enabled: "true"
      metricsExpiryDuration: "720h"
      scrape: true
      install:
        service:
          metadata:
            annotations:
              service.alpha.openshift.io/serving-cert-secret-name: prometheus-tls
          ingress:
            enabled: true
  runtime:
    components:
      pilot:
        deployment:
          replicas: 2
        pod:
          affinity: {}
        container:
          resources:
          limits: {}
          requirements: {}
      grafana:
        deployment: {}
        pod: {}
      kiali:
        deployment: {}
        pod: {}
---
# Source: service-mesh/templates/98-servicemesh-control-plane.yaml
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: "product-development"
  namespace: "product-development-mesh"
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "98"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "98"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  version: "v2.6"
  security:
    controlPlane:
      mtls: "true"
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
  general:
    logging:
      logAsJSON: true
      componentLevels:
        default: info
  profiles:
    - default
  proxy:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
    accessLogging:
      file:
        name: /dev/stdout
    networking:
      trafficControl:
        inbound: {}
        outbound:
          policy: REGISTRY_ONLY
  gateways:
    enabled: "true"
    egress:
      enabled: "true"
      runtime:
        deployment:
          autoScaling:
            enabled: true
            maxReplicas: 3
            minReplicas: 1
        pod: {}
      service: {}
    ingress:
      enabled: "true"
      runtime:
        deployment:
          autoScaling:
            enabled: true
            maxReplicas: 2
            minReplicas: 1
        pod: {}
      service: {}
    openshiftRoute:
      enabled: "false"
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: "true"
      install:
        config:
          env: {}
          envSecrets: {}
        persistence:
          storageClassName: ""
          accessMode: ReadWriteOnce
          capacity:
            requests:
              storage: 10Gi
          enabled: true
        service:
          metadata:
            annotations:
              service.alpha.openshift.io/serving-cert-secret-name: grafana-tls
          ingress:
            contextPath: /grafana
            tls:
              termination: reencrypt
    jaeger:
      install:
        enabled: "true"
    kiali:
      enabled: "true"
      name: kiali
      install:
        dashboard:
          viewOnly: false
        deployment:
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
        service:
          ingress:
            enabled: true
    prometheus:
      enabled: "true"
      metricsExpiryDuration: "720h"
      scrape: true
      install:
        service:
          metadata:
            annotations:
              service.alpha.openshift.io/serving-cert-secret-name: prometheus-tls
          ingress:
            enabled: true
  runtime:
    components:
      pilot:
        deployment:
          replicas: 2
        pod:
          affinity: {}
        container:
          resources:
          limits: {}
          requirements: {}
      grafana:
        deployment: {}
        pod: {}
      kiali:
        deployment: {}
        pod: {}
---
# Source: service-mesh/templates/99-servicemesh-member-roll.yaml
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: "default"
  namespace: "sales-mesh"
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "99"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "99"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  members:
    # a list of projects to join the service mesh
    
    - warehouse
    - point-of-sale
    - shipping
---
# Source: service-mesh/templates/99-servicemesh-member-roll.yaml
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: "default"
  namespace: "product-development-mesh"
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "99"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "99"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  members:
    # a list of projects to join the service mesh
    
    - r-and-d
    - quality-assurance
    - factory-procurement
