---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: {{ .Values.idp.aad.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  schedule: "{{ .Values.idp.aad.syncCronSchedule }}"
  providers:
    - azure:
        credentialsSecret:
          name: {{ .Values.idp.aad.clientSecretKeyVaultSecretName }}
          namespace: {{ .Values.namespace }}
          kind: Secret
        prune: false
        groups: {{ toYaml .Values.idp.aad.groups | nindent 12 }}
      name: {{ .Values.idp.aad.name }}
      
