{{ if .Values.enableAutoScale }}
---
apiVersion: "autoscaling.openshift.io/v1"
kind: "ClusterAutoscaler"
metadata:
  name: default
  annotations:
    # argocd.argoproj.io/sync-wave: "0"
    # # "helm.sh/hook": ""
    "helm.sh/hook-weight": "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  podPriorityThreshold: -10 
  resourceLimits:
    maxNodesTotal: {{ .Values.cluster.maxNodesCount }}
    cores:
      min: {{ .Values.cluster.cpu.min }}
      max: {{ .Values.cluster.cpu.max }} 
    memory:
      min: {{ .Values.cluster.memory.min }}
      max: {{ .Values.cluster.memory.max }}
    {{ if .Values.cluster.gpus.enable }}
    gpus:
      {{ toYaml .Values.cluster.gpus.devices }}
    {{ end }}
  logVerbosity: 4 
  scaleDown: 
    enabled: true 
    delayAfterAdd: {{ .Values.cluster.delayAfterAdd }}
    delayAfterDelete: {{ .Values.cluster.delayAfterDelete }}
    delayAfterFailure: {{ .Values.cluster.delayAfterFailure }} 
    unneededTime: {{ .Values.cluster.unneededTime }}
    utilizationThreshold: "{{ .Values.cluster.utilizationThreshold }}"
{{ end }}