{{ if .Values.enableAutoScale }}
---
{{- range $machinetSetItem := .Values.machineSets }}
apiVersion: "autoscaling.openshift.io/v1beta1"
kind: "MachineAutoscaler"
metadata:
  name: "{{ $machinetSetItem.name }}" 
  namespace: "openshift-machine-api"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  minReplicas: {{ $machinetSetItem.minReplicas }}
  maxReplicas: {{ $machinetSetItem.maxReplicas }} 
  scaleTargetRef: 
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet 
    name: "{{ $machinetSetItem.name }}"
---
{{- end }}
{{ end }}