apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.splunkHecSecretName }}
  namespace: "{{ .Values.splunk-otel-collector.namespaceOverride }}"
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  # Interval of time the Secret will be synchronized from secret provider (ie: AWS, Azure, GCP)
  refreshInterval: 5m

  # Name of the SecretStore/ClusterSecretStore - Used for authn against secret provider
  secretStoreRef:
    kind: ClusterSecretStore
    name: "{{ .Values.keyVaultName }}"

  # Name of the Secret to be created
  target:
    name: {{ .Values.splunkHecSecretName }}
    creationPolicy: "Owner"
    template:
      # Possible Values: "Opaque", "kubernetes.io/dockerconfigjson", "kubernetes.io/tls", "kubernetes.io/ssh-auth"
      type: Opaque

    dataFrom:
      - extract:
          key: {{ .Values.splunkKVSecretName }}